#!/bin/bash
set -euo pipefail
# set -x

echo "Fetching script from the web..."
URL="https://raw.githubusercontent.com/danrabinowitz/arch-install/master/files/remote/setup-script"


LOCAL_SCRIPT_FILENAME="/usr/local/sbin/custom-setup-script"
curl -fs -o "$LOCAL_SCRIPT_FILENAME" "$URL"
chmod 700 "$LOCAL_SCRIPT_FILENAME"

echo "Running ${LOCAL_SCRIPT_FILENAME}"
exec "$LOCAL_SCRIPT_FILENAME"
