#!/bin/bash
set -euo pipefail
# set -x

/run/archiso/bootmnt/custom_files/install/usr/local/sbin/copy_custom_files

/usr/local/sbin/custom-net-connect
echo "Starting sshd..."
systemctl start sshd

echo "Now connect via ssh and run: /usr/local/sbin/custom-run-remote-setup-script"
echo "Alternately, you can run that script directly from a local shell."
