#!/bin/bash
set -euo pipefail

echo "This is post-install-setup writing to /dev/console" > /dev/console

VERBOSE=1

if [ $VERBOSE -ne 0 ]; then
  set -x
fi

# Check if this has already been run before
head /var/log/post-install-setup.log

ls -l /var/run

if [ -f /var/run/post-install-setup ]; then
  echo "It appears that this post-install-setup script has been run before. Refusing to re-run. Aborting."
  exit 0
fi

echo "started" >> /var/run/post-install-setup
cat /var/run/post-install-setup

if [ $VERBOSE -ne 0 ]; then
  echo "Start of post-install-setup"
fi
echo "MSG2: This is post-install-setup writing to /dev/console" > /dev/console

function network_manager {
  # pacman --noconfirm -S \
  #   networkmanager

#   cat <<EOF > /etc/NetworkManager/conf.d/dhcp-client.conf
# [main]
# dhcp=dhclient
# EOF

#   systemctl enable NetworkManager.service
  # systemctl disable dhcpcd
  # DEV="wlp1s0"
  # systemctl disable dhcpcd@"$DEV"
}

function install_drivers {
  pacman -Syy

  pacman --noconfirm -S \
    xf86-input-synaptics
}

function install_and_setup_x {
  # Display Manager: LightDM
  # Greeter: lightdm-gtk3-greeter
  pacman --noconfirm -S \
    lightdm lightdm-gtk3-greeter \
    xfce4 xfce4-goodies \
    xfce4-notifyd xfce4-power-manager


  # Enable the newly installed Light display manager (LightDM) so you can use it when we reboot.
  systemctl enable lightdm.service

  # https://wiki.archlinux.org/index.php/Xfce#Lock_the_screen
}

function cleanup {
  systemctl disable post-install
  # rm /etc/systemd/system/post-install.service
}

function run {
  # network_manager
  install_drivers
  install_and_setup_x
  cleanup
}
run


# https://wiki.archlinux.org/index.php/NetworkManager#Problems_with_internal_DHCP_client
